name: Deploy Angular App to GitHub Pages

on: 
  push: 
    branches: 
      - main #Set this to your default branch

jobs: 
  build:
    runs-on: ubuntu-latest


    #Utilizar NAME(NOME) que ajuda a facilitar o que o USES está fazendo, pois ajuda na rastreabilidade de erros.
    steps: 
    - name: Checkout code
      uses: actions/checkout@v3  #Vai analisar seu código para verificar possiveis erros.

    - name: Set up Node.js
      uses: actions/setup-node@v3 
      with: 
        node-version: '18' 

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Run unit tests
      run: ng test --watch=false --browsers=ChromeHeadless

    - name: Build the app
      run: ng build --prod --base href  "https://rnNathan.github.io/actions/"

    deploy: 
      runs-on: ubuntu-latest
      needs: build

      steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs/
    